# Use the official Node.js 14 image as the base image
FROM node:16

# Install pnpm
RUN npm install -g pnpm

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml files to the container
COPY package*.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application code to the container
COPY . .

# Build the application
RUN pnpm run build

# Expose port 5173
EXPOSE 5173

# Start the application #TODO change to production
CMD ["pnpm", "run", "dev" ]
